### ISSUE TITLE
Settings system refactor

### ISSUE THREAD

**Issue by iamanai** [iamanai/ModernGadgets#16]
Multiple issues have popped up with the settings system, such that it needs to be fully redesigned. The settings will move back to being local, with changes being automatically copied to the external location as a backup. After updating, the values in the external files will be copied back in so settings will still be preserved.

The ReadINI and WriteINI functions will no longer be directly used to edit the files. They will only be used to compare values.

Also, functionality must be added to make the imported backup affect the skin INI's as well as the variables. This was an oversight in v1.0.0 that must be corrected.

It should also be noted that settings backups can be turned off through the global settings skin.

## To-do
- [x] Move settings management and update checking functionalities out of gadget manager and into a dedicated (invisible) skin
- [x] Rename 'ReferenceFiles' subfolder to 'Settings'
- [x] Create 'Defaults' subfolder to contain default settings (will remain unchanged)
- [x] Implement 'invokeAllSettings()' function into all gadget settings scripts, which will invoke all the settings changes for each script with the current variable values
- [x] Implement 'setDefaults()' function into all gadget settings scripts, similar to invokeAllSettings(), but with the default values
- [x] Completely scrap SettingsManagement.lua
- [x] Write new 'SettingsBackup.lua' script with the backup functionality described above
- [x] Implement backups toggle in global settings skin

## Notes
- This will fix all problems relating to nonexistent settings files, since they will now always exist
- Upon updating, the settings will all have reset. The invisible config skin will check for the existence of a backup. If the backup exists, it will automatically transfer the values to the local settings files, then it will invoke all the config scripts for each gadget, changing each gadget's configuration to match those settings before refreshing them
- If no backup exists, it will be assumed that it is a new installation
- Currently debating whether or not it should be an option to have backups

**Comment by iamanai** [comment]
Just had a brain wave. Need to write this down before I forget it!

- The parts of the scripts that change the gadgets' INIs directly need to be separated out and all shoved into the setup skin
- The gadget settings skins will only change their toggle buttons, and invoke the corresponding function through the setup skin
- This will allow the setup skin to update the gadgets after importing a backup, as well as reset them to defaults.

**Comment by iamanai** [comment]
DOOOONE!
