### ISSUE TITLE
CPU Meter not toggling thread measures

### ISSUE THREAD

**Issue by iamanai** [iamanai/ModernGadgets#23]
Thanks to MastroMicio for reporting this bug. The CPU Config Script doesn't actually enable/disable CPU usage and Core Temp measures like it is supposed to.

### To-do
- [ ] Add measures to groups by thread number
- [ ] Add !EnableMeasureGroup and !DisableMeasureGroup bangs to the CPU config script
- [ ] Enable/disable the clock speed measures, accounting for hyperthreading
