### ISSUE TITLE
Switch to Direct2D font rendering

### ISSUE THREAD

**Issue by iamanai** [iamanai/ModernGadgets#24]
[This section](https://docs.rainmeter.net/manual/skins/rainmeter-section/#AccurateText) in the Rainmeter documentation describes a feature that was introduced back in Rainmeter 3.0. It details an option that will use Direct2D to render fonts, rather than what it normally uses (the name escapes me).

The advantages to using this is that the fonts will be much more readable, and the boundaries of text meters will be WAY more consistent. This will allow greater simplification of positioning equations and will introduce an overall cleaner look.

However, it won't come without issues. In initial testing, switching to Direct2D completely messes up the positioning of text, and makes the bar lines appear way closer to the text they are under. It also makes the text appear smaller overall, and increasing the font size by 1 makes it too big (maybe apply bolding to all text?) The positioning equations and options in the config scripts will all have to be redone, which will take time.

### To-do
- [x] Activate Direct2D on all skins
- [x] Fix font size and style (will probably need to go bold)
- [x] Fix text positioning and content margins
- [x] Fix bar line positioning under meters
- [x] Update graph positioning functions
- [x] Update settings and config scripts to account for the new positioning
