### ISSUE TITLE
Thermal Throttling Detection

### ISSUE THREAD

**Issue by iamanai** [iamanai/ModernGadgets#26]
Enhancement for CPU Meter to display when thermal throttling gets enabled. Will change the CPU icon to a warning icon, play a warning sound (optional), and add a red tint to the line graph (histogram at 100%). Users will be able to disable this warning, control the volume of the sound, and disable the sound if they so desire.

### To-do
- [x] Add necessary meters
- [x] Add HWiNFO measure
- [x] Add value to HWiNFO tool
- [x] Add toggle in CPU Meter settings
