### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by iamanai** [iamanai/ModernGadgets#28]
Each gadget's config skin will have a tab for color customization. The customizable colors will be those shown on line graphs and bars, as well as arrows. To change a color, the user clicks on the color in a list and uses RainRGB. Alpha values cannot be changed.

### To-do
- [x] Find a good way to add a color customization tab to the config skins
- [x] Create template for changing a color
#### CPU Meter
- [x] Core usages (1-20) and average usage
- [x] RAM and page file usage
- [x] Fan speed (for alternate fan display)
#### Network Meter
- [x] Upload rate
- [ ] Download rate
#### GPU Meter
- [x] Core usage
- [x] Fan speed
- [x] VRAM usage
- [x] Memory Controller usage
#### Disks Meter
- [x] Disks 1-26 (ugh)
