### ISSUE TITLE
Network Meter: Show Ping

### ISSUE THREAD

**Issue by iamanai** [iamanai/ModernGadgets#29]
[The "Ping" Plugin](https://docs.rainmeter.net/manual/plugins/ping/) can be used to find the ping to certain websites. This could allow Network Meter to check the ping periodically, and display it if the user so desires. The destination website can be changed via the config skin.

### To-do
- [x] Add ping measure, counter measure, and URL variable
- [x] Add meter to Network Meter
- [x] Create toggle and URL input in config skin
