### ISSUE TITLE
Skin Scaling

### ISSUE THREAD

**Issue by iamanai** [iamanai/ModernGadgets#33]
Utilize TransformationMatrix to make the gadgets and config skins scalable. This ability would mostly be useful for those with 4K monitors, where the default gadget size is too small. Will be freely changeable using an input box, and right-clicking on the global settings skin (where the input box will be) will offer a context option to revert to default sizing in case a user accidentally makes it too large.

## To-do
- [x] Implement transformationmatrix on all meters
- [ ] Add SkinWidth and SkinHeight parameters to all skins
- [ ] Fix positioning equations to account for transformationmatrix
- [ ] Add transparent image meters to allow for mouseactions to work at non-default sizes

**Comment by raiguard** [comment]
So this will be possible if I stop using the “border” image and make every border four separate images. I will also need to add invisible button meters to EVERY button. *sigh*

**Comment by SerVB** [comment]
Actually, I don't like the idea of hardcoded constants. I think they prevent from implementing scaling easily.

**Comment by raiguard** [comment]
What hardcoded constants?

**Comment by SerVB** [comment]
For example that font size: https://github.com/raiguard/ModernGadgets/commit/e4309abbbfce000862431f836691cc5a9427df9c . I'm not certain, but maybe it would be better to make a global constant `#CommonIconFontSize#` with a value of 10 (`FontSize=#CommonIconFontSize#`) instead of `FontSize=10`.

So implementing scaling will look like `FontSize=#CommonIconFontSize# * #ScaleFactor#`. It would be harder to have scaling bugs because using the same global constants changes sizes of everything similarly.

As I understand, hardcoding is a coding style of the project. Currently, many numbers are equal by value and by sense, but those values are hardcoded. So changing something in one place will cause many identical changes in others.

Maybe I don't know something about Rainmeter (I'm a really newbie) and everything I've written has no use at all :(
What do you think?

**Comment by SerVB** [comment]
Some more examples:
![image](https://user-images.githubusercontent.com/20105593/37782802-e546ee32-2e04-11e8-9b75-3fb71d936f3e.png)
![image](https://user-images.githubusercontent.com/20105593/37782838-fd45f668-2e04-11e8-969c-96e7fc2fe56c.png)

**Comment by raiguard** [comment]
I actually have a local branch on my PC in which I implemented TransformationMatrix. However, none of the buttons work at any size except 1.0, and there are still visual hiccups to sort out. I’ll publish the branch when I get home so you can check it out.

**Comment by raiguard** [comment]
So thanks to jsmorley, I now know a way to implement this while retaining the relative positioning equations that I'm currently using! So this feature will possibly come in v1.5.0!

**Comment by raiguard** [comment]
:D

![2018-10-16 22_54_00-](https://user-images.githubusercontent.com/3515394/47063023-afd3e800-d196-11e8-8021-455cae7aaadc.png)

Making progress!

**Comment by raiguard** [comment]
![transform](https://user-images.githubusercontent.com/3515394/47260025-9ff72500-d470-11e8-90db-dc59988a6f07.gif)
1x vs. 5x scale.

**Comment by raiguard** [comment]
All of the system monitoring gadgets now have scaling support! I still need to to chronometer, the new v1.5 gadgets, ALL of the configuration skins, and the setup skin. :(
![2018-10-20 14_12_31-](https://user-images.githubusercontent.com/3515394/47260124-53ace480-d472-11e8-92b3-4c971fbec8c9.png)

**Comment by raiguard** [comment]
![img_20181020_153445](https://user-images.githubusercontent.com/3515394/47260712-f028b400-d47d-11e8-99bc-5bd2a6a4a37d.jpg)
Bigger == better, right?

**Comment by raiguard** [comment]
So I discovered that it is flat-out impossible to scale input boxes. Thus, all of the settings skins are forced to stay at x1 scale, with the scale setting only affecting the actual Gadgets themselves. However, on the bright side, that means that scaling support is almost completely finished now! It'll be included in the first v1.5 beta.

**Comment by SerVB** [comment]
1.5.0-beta1 welcomes me not properly :)

![image](https://user-images.githubusercontent.com/20105593/47421410-384f1b80-d789-11e8-9e06-77eb88fa4be4.png)

As you see, the button is out of bounds.

**Comment by raiguard** [comment]
This is the kind of thing that should be put into the 'scaling beta test' issue. But in this case, this is a known bug that I am trying to solve, but currently don't know how to. I am working on it though!

**Comment by SerVB** [comment]
@raiguard, now there is the same update prompt glitch:

![image](https://user-images.githubusercontent.com/20105593/47954519-e897fd80-df9b-11e8-92b5-014ca63bb161.png)

It appears on 1.5.0-beta1. I use 1.00 scale factor.

By the way, should I write about it here or [there](https://github.com/raiguard/ModernGadgets/issues/115)?

**Comment by raiguard** [comment]
I fixed that issue in beta 2. And yes, this is what that other issue is meant for.
