### ISSUE TITLE
Global settings skin

### ISSUE THREAD

**Issue by iamanai** [iamanai/ModernGadgets#6]
Skin to change settings that apply to all gadgets. Will include background border, row spacing, and temperature units. Will also have update notification options, including opting in to testing development versions, settings backups options, and a "reset to defaults" button.

Depends on #16.

## To-do
- [x] Base skin (background, close button, etc.)
- [x] Global settings script
- [x] Background border
- [x] Show temperatures in Fahrenheit
- [x] Large row spacing
- [x] Automatically notify of available updates
- [x] Opt-in to development versions
- [x] Settings backups
- [x] Line Graph antialiasing
- [x] Reset all settings to default

**Comment by iamanai** [comment]
It's done now, but it always refreshes all skins when changing a setting. This needs to be remedied in the future.
